[versions]
agp = "8.2.0"
kotlin = "1.9.21"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
api-xposed = "de.robv.android.xposed:api:82"